# Generated by Django 5.2.8 on 2025-11-08 00:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("Companies", "0001_initial"),
        ("Jobs", "0001_initial"),
        ("Oauth", "0002_userprofiles"),
    ]

    operations = [
        migrations.CreateModel(
            name="LearningPaths",
            fields=[
                ("id", models.UUIDField(primary_key=True, serialize=False)),
                ("title", models.CharField(max_length=255)),
                ("description", models.TextField(blank=True, null=True)),
                (
                    "target_role",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                ("estimated_hours", models.IntegerField(blank=True, null=True)),
                (
                    "difficulty_level",
                    models.CharField(blank=True, max_length=20, null=True),
                ),
                ("completion_percentage", models.IntegerField(blank=True, null=True)),
                ("status", models.CharField(blank=True, max_length=20, null=True)),
                ("created_at", models.DateTimeField(blank=True, null=True)),
                ("updated_at", models.DateTimeField(blank=True, null=True)),
                ("completed_at", models.DateTimeField(blank=True, null=True)),
                (
                    "target_job",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        to="Jobs.jobs",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.DO_NOTHING, to="Oauth.users"
                    ),
                ),
            ],
            options={
                "db_table": "learning_paths",
                "managed": True,
            },
        ),
        migrations.CreateModel(
            name="LearningPathSteps",
            fields=[
                ("id", models.UUIDField(primary_key=True, serialize=False)),
                ("step_order", models.IntegerField()),
                ("title", models.CharField(max_length=255)),
                ("description", models.TextField(blank=True, null=True)),
                (
                    "resource_type",
                    models.CharField(blank=True, max_length=50, null=True),
                ),
                ("resource_url", models.TextField(blank=True, null=True)),
                ("estimated_hours", models.IntegerField(blank=True, null=True)),
                ("is_completed", models.BooleanField(blank=True, null=True)),
                ("completed_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(blank=True, null=True)),
                (
                    "learning_path",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        to="Personalization.learningpaths",
                    ),
                ),
            ],
            options={
                "db_table": "learning_path_steps",
                "managed": True,
            },
        ),
        migrations.CreateModel(
            name="Locations",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("city", models.CharField(max_length=100)),
                ("state", models.CharField(blank=True, max_length=100, null=True)),
                ("country", models.CharField(max_length=100)),
                ("country_code", models.CharField(max_length=2)),
                ("coordinates", models.JSONField(blank=True, null=True)),
                ("is_remote", models.BooleanField(blank=True, null=True)),
                ("region", models.CharField(blank=True, max_length=100, null=True)),
                ("total_jobs", models.IntegerField(blank=True, null=True)),
                ("active_jobs", models.IntegerField(blank=True, null=True)),
                ("created_at", models.DateTimeField(blank=True, null=True)),
                ("updated_at", models.DateTimeField(blank=True, null=True)),
            ],
            options={
                "db_table": "locations",
                "managed": True,
                "unique_together": {("city", "state", "country")},
            },
        ),
        migrations.CreateModel(
            name="SkillGapAnalyses",
            fields=[
                ("id", models.UUIDField(primary_key=True, serialize=False)),
                (
                    "match_score",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=5, null=True
                    ),
                ),
                ("missing_skills", models.TextField(blank=True, null=True)),
                ("matching_skills", models.TextField(blank=True, null=True)),
                ("nice_to_have_skills", models.TextField(blank=True, null=True)),
                ("analysis_text", models.TextField(blank=True, null=True)),
                ("recommendations", models.TextField(blank=True, null=True)),
                (
                    "estimated_time_to_ready",
                    models.CharField(blank=True, max_length=50, null=True),
                ),
                ("analyzed_at", models.DateTimeField(blank=True, null=True)),
                (
                    "ai_model_used",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                (
                    "job",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        to="Jobs.jobs",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.DO_NOTHING, to="Oauth.users"
                    ),
                ),
            ],
            options={
                "db_table": "skill_gap_analyses",
                "managed": True,
            },
        ),
        migrations.CreateModel(
            name="UserCompanyFollows",
            fields=[
                ("id", models.UUIDField(primary_key=True, serialize=False)),
                ("followed_at", models.DateTimeField(blank=True, null=True)),
                (
                    "notification_preference",
                    models.CharField(blank=True, max_length=20, null=True),
                ),
                ("match_score", models.IntegerField(blank=True, null=True)),
                ("last_interaction", models.DateTimeField(blank=True, null=True)),
                ("interaction_count", models.IntegerField(blank=True, null=True)),
                (
                    "company",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        to="Companies.companies",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.DO_NOTHING, to="Oauth.users"
                    ),
                ),
            ],
            options={
                "db_table": "user_company_follows",
                "managed": True,
                "unique_together": {("user", "company")},
            },
        ),
    ]
