# Generated by Django 5.2.8 on 2026-06-22 04:01

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


def convert_legacy_user_fk_sql(table_name):
    index_name = f"{table_name}_user_id_auth_idx"
    constraint_name = f"{table_name}_user_id_auth_fk"
    return f"""
DO $$
DECLARE
    user_col_type text;
    old_fk_name text;
BEGIN
    SELECT format_type(a.atttypid, a.atttypmod)
      INTO user_col_type
      FROM pg_attribute a
     WHERE a.attrelid = '{table_name}'::regclass
       AND a.attname = 'user_id'
       AND NOT a.attisdropped;

    IF user_col_type = 'uuid' THEN
        ALTER TABLE {table_name} ADD COLUMN IF NOT EXISTS user_auth_id integer;

        UPDATE {table_name} target
           SET user_auth_id = auth_user.id
          FROM users legacy_user
          JOIN auth_user ON lower(auth_user.email) = lower(legacy_user.email)
         WHERE target.user_id = legacy_user.id
           AND target.user_auth_id IS NULL;

        IF EXISTS (
            SELECT 1
              FROM {table_name} target
              LEFT JOIN users legacy_user ON target.user_id = legacy_user.id
              LEFT JOIN auth_user ON lower(auth_user.email) = lower(legacy_user.email)
             WHERE target.user_id IS NOT NULL
               AND auth_user.id IS NULL
        ) THEN
            RAISE EXCEPTION 'Cannot migrate %.user_id: legacy user has no matching auth_user email', '{table_name}';
        END IF;

        SELECT conname
          INTO old_fk_name
          FROM pg_constraint
         WHERE conrelid = '{table_name}'::regclass
           AND contype = 'f'
           AND conkey = ARRAY[
               (SELECT attnum FROM pg_attribute WHERE attrelid = '{table_name}'::regclass AND attname = 'user_id')
           ]
         LIMIT 1;

        IF old_fk_name IS NOT NULL THEN
            EXECUTE format('ALTER TABLE {table_name} DROP CONSTRAINT %I', old_fk_name);
        END IF;

        ALTER TABLE {table_name} DROP COLUMN user_id;
        ALTER TABLE {table_name} RENAME COLUMN user_auth_id TO user_id;
        ALTER TABLE {table_name} ALTER COLUMN user_id SET NOT NULL;
        ALTER TABLE {table_name}
            ADD CONSTRAINT {constraint_name}
            FOREIGN KEY (user_id) REFERENCES auth_user(id)
            DEFERRABLE INITIALLY DEFERRED;
        CREATE INDEX IF NOT EXISTS {index_name} ON {table_name}(user_id);
    END IF;
END $$;
"""


class Migration(migrations.Migration):

    dependencies = [
        ('Personalization', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.SeparateDatabaseAndState(
            database_operations=[
                migrations.RunSQL(
                    convert_legacy_user_fk_sql('learning_paths'),
                    reverse_sql=migrations.RunSQL.noop,
                ),
                migrations.RunSQL(
                    convert_legacy_user_fk_sql('skill_gap_analyses'),
                    reverse_sql=migrations.RunSQL.noop,
                ),
                migrations.RunSQL(
                    convert_legacy_user_fk_sql('user_company_follows'),
                    reverse_sql=migrations.RunSQL.noop,
                ),
            ],
            state_operations=[
                migrations.AlterField(
                    model_name='learningpaths',
                    name='user',
                    field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL),
                ),
                migrations.AlterField(
                    model_name='skillgapanalyses',
                    name='user',
                    field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL),
                ),
                migrations.AlterField(
                    model_name='usercompanyfollows',
                    name='user',
                    field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL),
                ),
            ],
        ),
    ]
