# Generated by Codex on 2026-06-22

import uuid

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Personalization", "0002_alter_learningpaths_user_alter_skillgapanalyses_user_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="UserMemory",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                (
                    "memory_type",
                    models.CharField(
                        choices=[
                            ("profile_fact", "Profile fact"),
                            ("career_goal", "Career goal"),
                            ("skill", "Skill"),
                            ("learning_interest", "Learning interest"),
                            ("preference", "Preference"),
                            ("negative_preference", "Negative preference"),
                            ("behavioral_signal", "Behavioral signal"),
                            ("trait", "Trait"),
                            ("persona_summary", "Persona summary"),
                            ("application_signal", "Application signal"),
                            ("company_interest", "Company interest"),
                            ("conversation", "Conversation"),
                        ],
                        max_length=40,
                    ),
                ),
                ("text", models.TextField()),
                ("source", models.CharField(blank=True, max_length=80, null=True)),
                ("source_object_type", models.CharField(blank=True, max_length=100, null=True)),
                ("source_object_id", models.CharField(blank=True, max_length=100, null=True)),
                ("confidence", models.DecimalField(decimal_places=3, default=1, max_digits=4)),
                ("importance", models.DecimalField(decimal_places=3, default=0.5, max_digits=4)),
                ("is_core", models.BooleanField(default=False)),
                ("is_active", models.BooleanField(default=True)),
                ("valid_from", models.DateTimeField(blank=True, null=True)),
                ("valid_until", models.DateTimeField(blank=True, null=True)),
                ("last_reinforced_at", models.DateTimeField(blank=True, null=True)),
                ("qdrant_point_id", models.CharField(blank=True, max_length=100, null=True)),
                ("metadata", models.JSONField(blank=True, default=dict, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="memories",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "user_memories",
                "managed": True,
            },
        ),
        migrations.CreateModel(
            name="UserBehaviorEvent",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                (
                    "event_type",
                    models.CharField(
                        choices=[
                            ("job_view", "Job view"),
                            ("job_click", "Job click"),
                            ("job_save", "Job save"),
                            ("job_apply", "Job apply"),
                            ("job_dismiss", "Job dismiss"),
                            ("company_follow", "Company follow"),
                            ("company_unfollow", "Company unfollow"),
                            ("search", "Search"),
                            ("learning_step_started", "Learning step started"),
                            ("learning_step_completed", "Learning step completed"),
                            ("recommendation_accepted", "Recommendation accepted"),
                            ("recommendation_rejected", "Recommendation rejected"),
                        ],
                        max_length=50,
                    ),
                ),
                ("object_type", models.CharField(blank=True, max_length=80, null=True)),
                ("object_id", models.CharField(blank=True, max_length=100, null=True)),
                ("event_value", models.DecimalField(blank=True, decimal_places=3, max_digits=8, null=True)),
                ("context", models.JSONField(blank=True, default=dict, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="behavior_events",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "user_behavior_events",
                "managed": True,
            },
        ),
        migrations.CreateModel(
            name="UserTrait",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("trait_key", models.CharField(max_length=100)),
                ("trait_value", models.CharField(max_length=255)),
                ("confidence", models.DecimalField(decimal_places=3, default=0.5, max_digits=4)),
                ("evidence_count", models.PositiveIntegerField(default=1)),
                ("last_evidence_at", models.DateTimeField(blank=True, null=True)),
                ("metadata", models.JSONField(blank=True, default=dict, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="traits",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "user_traits",
                "managed": True,
                "unique_together": {("user", "trait_key", "trait_value")},
            },
        ),
        migrations.AddIndex(
            model_name="usermemory",
            index=models.Index(fields=["user", "memory_type", "is_active"], name="user_memori_user_id_924ad0_idx"),
        ),
        migrations.AddIndex(
            model_name="usermemory",
            index=models.Index(fields=["source", "source_object_type", "source_object_id"], name="user_memori_source_d927b1_idx"),
        ),
        migrations.AddIndex(
            model_name="usermemory",
            index=models.Index(fields=["qdrant_point_id"], name="user_memori_qdrant__59816d_idx"),
        ),
        migrations.AddIndex(
            model_name="userbehaviorevent",
            index=models.Index(fields=["user", "event_type", "created_at"], name="user_behavi_user_id_fe61fe_idx"),
        ),
        migrations.AddIndex(
            model_name="userbehaviorevent",
            index=models.Index(fields=["object_type", "object_id"], name="user_behavi_object__edd193_idx"),
        ),
        migrations.AddIndex(
            model_name="usertrait",
            index=models.Index(fields=["user", "trait_key"], name="user_traits_user_id_c6e42a_idx"),
        ),
    ]
