# Generated by Django 5.2.8 on 2025-11-08 00:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="ApplicationEvents",
            fields=[
                ("id", models.UUIDField(primary_key=True, serialize=False)),
                ("event_type", models.CharField(blank=True, max_length=30, null=True)),
                ("event_date", models.DateTimeField()),
                ("title", models.CharField(blank=True, max_length=200, null=True)),
                ("description", models.TextField(blank=True, null=True)),
                (
                    "interviewer_name",
                    models.CharField(blank=True, max_length=200, null=True),
                ),
                (
                    "interviewer_title",
                    models.CharField(blank=True, max_length=200, null=True),
                ),
                ("location", models.CharField(blank=True, max_length=255, null=True)),
                ("duration_minutes", models.IntegerField(blank=True, null=True)),
                (
                    "offer_amount",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=12, null=True
                    ),
                ),
                (
                    "offer_currency",
                    models.CharField(blank=True, max_length=10, null=True),
                ),
                ("notes", models.TextField(blank=True, null=True)),
                ("preparation_notes", models.TextField(blank=True, null=True)),
                ("outcome", models.CharField(blank=True, max_length=50, null=True)),
                ("reminder_set", models.BooleanField(blank=True, null=True)),
                ("reminder_datetime", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(blank=True, null=True)),
                ("updated_at", models.DateTimeField(blank=True, null=True)),
            ],
            options={
                "db_table": "application_events",
                "managed": True,
            },
        ),
        migrations.CreateModel(
            name="Applications",
            fields=[
                ("id", models.UUIDField(primary_key=True, serialize=False)),
                ("company_name", models.CharField(max_length=255)),
                ("job_title", models.CharField(max_length=255)),
                ("status", models.CharField(blank=True, max_length=20, null=True)),
                ("applied_date", models.DateField()),
                ("application_url", models.TextField(blank=True, null=True)),
                ("source", models.CharField(blank=True, max_length=50, null=True)),
                (
                    "salary_range",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                ("location", models.CharField(blank=True, max_length=255, null=True)),
                ("work_type", models.CharField(blank=True, max_length=50, null=True)),
                ("notes", models.TextField(blank=True, null=True)),
                ("cover_letter", models.TextField(blank=True, null=True)),
                (
                    "resume_version",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                ("interview_dates", models.TextField(blank=True, null=True)),
                ("interview_notes", models.TextField(blank=True, null=True)),
                (
                    "next_action",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                ("next_action_date", models.DateField(blank=True, null=True)),
                ("follow_up_count", models.IntegerField(blank=True, null=True)),
                ("rejection_reason", models.TextField(blank=True, null=True)),
                ("feedback_received", models.TextField(blank=True, null=True)),
                ("offer_details", models.JSONField(blank=True, null=True)),
                ("created_at", models.DateTimeField(blank=True, null=True)),
                ("updated_at", models.DateTimeField(blank=True, null=True)),
                ("last_status_change", models.DateTimeField(blank=True, null=True)),
            ],
            options={
                "db_table": "applications",
                "managed": True,
            },
        ),
        migrations.CreateModel(
            name="ApplicationStatusHistory",
            fields=[
                ("id", models.UUIDField(primary_key=True, serialize=False)),
                ("old_status", models.CharField(blank=True, max_length=20, null=True)),
                ("new_status", models.CharField(max_length=20)),
                ("changed_by_user", models.BooleanField(blank=True, null=True)),
                ("notes", models.TextField(blank=True, null=True)),
                ("created_at", models.DateTimeField(blank=True, null=True)),
            ],
            options={
                "db_table": "application_status_history",
                "managed": True,
            },
        ),
        migrations.CreateModel(
            name="EmailTracking",
            fields=[
                ("id", models.UUIDField(primary_key=True, serialize=False)),
                ("email_id", models.CharField(max_length=255, unique=True)),
                ("thread_id", models.CharField(blank=True, max_length=255, null=True)),
                ("subject", models.CharField(blank=True, max_length=500, null=True)),
                ("sender", models.CharField(blank=True, max_length=255, null=True)),
                (
                    "sender_name",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                ("received_at", models.DateTimeField()),
                ("body_text", models.TextField(blank=True, null=True)),
                ("body_html", models.TextField(blank=True, null=True)),
                ("email_type", models.CharField(blank=True, max_length=30, null=True)),
                (
                    "company_identified",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "job_title_identified",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "confidence_score",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=3, null=True
                    ),
                ),
                ("is_processed", models.BooleanField(blank=True, null=True)),
                (
                    "processing_status",
                    models.CharField(blank=True, max_length=20, null=True),
                ),
                ("processed_at", models.DateTimeField(blank=True, null=True)),
                ("error_message", models.TextField(blank=True, null=True)),
                ("application_created", models.BooleanField(blank=True, null=True)),
                ("event_created", models.BooleanField(blank=True, null=True)),
                ("user_notified", models.BooleanField(blank=True, null=True)),
                (
                    "ai_model_used",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                ("extraction_data", models.JSONField(blank=True, null=True)),
                ("created_at", models.DateTimeField(blank=True, null=True)),
                ("updated_at", models.DateTimeField(blank=True, null=True)),
            ],
            options={
                "db_table": "email_tracking",
                "managed": True,
            },
        ),
    ]
