# Generated by Django 5.2.8 on 2025-11-08 00:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("Applications", "0001_initial"),
        ("Jobs", "0001_initial"),
        ("Oauth", "0002_userprofiles"),
    ]

    operations = [
        migrations.AddField(
            model_name="applications",
            name="job",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                to="Jobs.jobs",
            ),
        ),
        migrations.AddField(
            model_name="applications",
            name="job_interest",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                to="Jobs.jobinterests",
            ),
        ),
        migrations.AddField(
            model_name="applications",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.DO_NOTHING, to="Oauth.users"
            ),
        ),
        migrations.AddField(
            model_name="applicationevents",
            name="application",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.DO_NOTHING,
                to="Applications.applications",
            ),
        ),
        migrations.AddField(
            model_name="applicationstatushistory",
            name="application",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.DO_NOTHING,
                to="Applications.applications",
            ),
        ),
        migrations.AddField(
            model_name="emailtracking",
            name="application",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                to="Applications.applications",
            ),
        ),
        migrations.AddField(
            model_name="emailtracking",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.DO_NOTHING, to="Oauth.users"
            ),
        ),
    ]
