# Generated by Django 5.2.8 on 2025-12-02 00:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("Applications", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="PendingInterviewConfirmation",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("email_thread_id", models.CharField(max_length=255)),
                ("gmail_message_id", models.CharField(max_length=255)),
                ("proposed_times", models.JSONField()),
                ("recruiter_email", models.EmailField(max_length=254)),
                ("company_name", models.CharField(max_length=200)),
                ("role", models.CharField(max_length=200)),
                ("stage", models.CharField(max_length=50)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("confirmed", "Confirmed"),
                            ("rejected", "Rejected"),
                        ],
                        default="pending",
                        max_length=20,
                    ),
                ),
                ("user_response", models.TextField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("confirmed_at", models.DateTimeField(blank=True, null=True)),
                (
                    "application",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="Applications.applications",
                    ),
                ),
            ],
            options={
                "db_table": "pending_interview_confirmations",
                "managed": True,
            },
        ),
    ]