# Generated by Django 5.2.8 on 2025-12-02 12:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("Applications", "0002_initial"),
        ("Applications", "0002_pending_interview_confirmation"),
    ]

    operations = []
