# Generated by Django 6.0.5 on 2026-07-05 09:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Applications", "0004_alter_applications_user_alter_emailtracking_user"),
    ]

    operations = [
        migrations.AddField(
            model_name="applications",
            name="is_auto_applied",
            field=models.BooleanField(default=False),
        ),
    ]
