# Generated by Django 5.2.8 on 2025-11-08 00:23

import django.contrib.postgres.fields
import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("Companies", "0001_initial"),
        ("Oauth", "0002_userprofiles"),
    ]

    operations = [
        migrations.CreateModel(
            name="JobCollectionLogs",
            fields=[
                ("id", models.UUIDField(primary_key=True, serialize=False)),
                ("status", models.CharField(blank=True, max_length=20, null=True)),
                ("started_at", models.DateTimeField(blank=True, null=True)),
                ("completed_at", models.DateTimeField(blank=True, null=True)),
                ("duration_seconds", models.IntegerField(blank=True, null=True)),
                ("jobs_requested", models.IntegerField(blank=True, null=True)),
                ("jobs_received", models.IntegerField(blank=True, null=True)),
                ("jobs_created", models.IntegerField(blank=True, null=True)),
                ("jobs_updated", models.IntegerField(blank=True, null=True)),
                ("jobs_skipped", models.IntegerField(blank=True, null=True)),
                ("errors_count", models.IntegerField(blank=True, null=True)),
                ("error_details", models.JSONField(blank=True, null=True)),
                ("collection_params", models.JSONField(blank=True, null=True)),
                ("api_response_meta", models.JSONField(blank=True, null=True)),
            ],
            options={
                "db_table": "job_collection_logs",
                "managed": True,
            },
        ),
        migrations.CreateModel(
            name="JobSources",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=50, unique=True)),
                ("base_url", models.TextField()),
                ("is_active", models.BooleanField(blank=True, null=True)),
                ("rate_limit_per_minute", models.IntegerField(blank=True, null=True)),
                ("last_collection_at", models.DateTimeField(blank=True, null=True)),
                ("total_jobs_collected", models.BigIntegerField(blank=True, null=True)),
                (
                    "success_rate",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=5, null=True
                    ),
                ),
                ("created_at", models.DateTimeField(blank=True, null=True)),
                ("updated_at", models.DateTimeField(blank=True, null=True)),
            ],
            options={
                "db_table": "job_sources",
                "managed": True,
            },
        ),
        migrations.CreateModel(
            name="JobInterests",
            fields=[
                ("id", models.UUIDField(primary_key=True, serialize=False)),
                (
                    "interest_type",
                    models.CharField(blank=True, max_length=20, null=True),
                ),
                ("clicked_url", models.TextField(blank=True, null=True)),
                (
                    "converted_to_application",
                    models.BooleanField(blank=True, null=True),
                ),
                (
                    "conversion_reminder_sent",
                    models.BooleanField(blank=True, null=True),
                ),
                ("reminder_sent_at", models.DateTimeField(blank=True, null=True)),
                (
                    "source_page",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                ("user_agent", models.TextField(blank=True, null=True)),
                ("ip_address", models.GenericIPAddressField(blank=True, null=True)),
                ("created_at", models.DateTimeField(blank=True, null=True)),
                ("updated_at", models.DateTimeField(blank=True, null=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.DO_NOTHING, to="Oauth.users"
                    ),
                ),
            ],
            options={
                "db_table": "job_interests",
                "managed": True,
            },
        ),
        migrations.CreateModel(
            name="JobMatchScores",
            fields=[
                ("id", models.UUIDField(primary_key=True, serialize=False)),
                (
                    "overall_score",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=5, null=True
                    ),
                ),
                (
                    "skill_match_score",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=5, null=True
                    ),
                ),
                (
                    "location_match_score",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=5, null=True
                    ),
                ),
                (
                    "salary_match_score",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=5, null=True
                    ),
                ),
                (
                    "experience_match_score",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=5, null=True
                    ),
                ),
                ("match_reasons", models.TextField(blank=True, null=True)),
                ("concerns", models.TextField(blank=True, null=True)),
                ("calculated_at", models.DateTimeField(blank=True, null=True)),
                (
                    "ai_model_used",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.DO_NOTHING, to="Oauth.users"
                    ),
                ),
            ],
            options={
                "db_table": "job_match_scores",
                "managed": True,
            },
        ),
        migrations.CreateModel(
            name="Jobs",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("external_id", models.CharField(max_length=255)),
                ("title", models.CharField(max_length=255)),
                ("slug", models.CharField(max_length=255)),
                ("description", models.TextField()),
                ("requirements", models.TextField(blank=True, null=True)),
                ("benefits", models.TextField(blank=True, null=True)),
                ("work_type", models.CharField(blank=True, max_length=20, null=True)),
                (
                    "experience_level",
                    models.CharField(blank=True, max_length=20, null=True),
                ),
                ("is_remote", models.BooleanField(blank=True, null=True)),
                ("is_hybrid", models.BooleanField(blank=True, null=True)),
                (
                    "salary_min",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=10, null=True
                    ),
                ),
                (
                    "salary_max",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=10, null=True
                    ),
                ),
                (
                    "salary_currency",
                    models.CharField(blank=True, max_length=3, null=True),
                ),
                (
                    "salary_period",
                    models.CharField(blank=True, max_length=20, null=True),
                ),
                (
                    "skills",
                    django.contrib.postgres.fields.ArrayField(
                        base_field=models.CharField(max_length=100),
                        blank=True,
                        default=list,
                        null=True,
                        size=None,
                    ),
                ),
                (
                    "technologies",
                    django.contrib.postgres.fields.ArrayField(
                        base_field=models.CharField(max_length=100),
                        blank=True,
                        default=list,
                        null=True,
                        size=None,
                    ),
                ),
                (
                    "categories",
                    django.contrib.postgres.fields.ArrayField(
                        base_field=models.CharField(max_length=100),
                        blank=True,
                        default=list,
                        null=True,
                        size=None,
                    ),
                ),
                ("external_url", models.TextField()),
                ("apply_url", models.TextField(blank=True, null=True)),
                ("status", models.CharField(blank=True, max_length=20, null=True)),
                ("posted_at", models.DateTimeField()),
                ("source_updated_at", models.DateTimeField()),
                ("ingested_at", models.DateTimeField(blank=True, null=True)),
                ("last_verified_at", models.DateTimeField(blank=True, null=True)),
                ("expires_at", models.DateTimeField(blank=True, null=True)),
                ("is_fresh", models.BooleanField(blank=True, null=True)),
                ("freshness_score", models.IntegerField(blank=True, null=True)),
                ("last_freshness_update", models.DateTimeField(blank=True, null=True)),
                ("view_count", models.IntegerField(blank=True, null=True)),
                ("apply_count", models.IntegerField(blank=True, null=True)),
                (
                    "quality_score",
                    models.DecimalField(
                        blank=True, decimal_places=1, max_digits=3, null=True
                    ),
                ),
                ("raw_data", models.JSONField(blank=True, null=True)),
                ("parsed_metadata", models.JSONField(blank=True, null=True)),
                ("created_at", models.DateTimeField(blank=True, null=True)),
                ("updated_at", models.DateTimeField(blank=True, null=True)),
                (
                    "company",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        to="Companies.companies",
                    ),
                ),
            ],
            options={
                "db_table": "jobs",
                "managed": True,
            },
        ),
    ]
