# Generated by Django 5.2.8 on 2025-11-08 00:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("Jobs", "0001_initial"),
        ("Personalization", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="jobs",
            name="location",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.DO_NOTHING,
                to="Personalization.locations",
            ),
        ),
        migrations.AddField(
            model_name="jobmatchscores",
            name="job",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.DO_NOTHING, to="Jobs.jobs"
            ),
        ),
        migrations.AddField(
            model_name="jobinterests",
            name="job",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.DO_NOTHING, to="Jobs.jobs"
            ),
        ),
        migrations.AddField(
            model_name="jobs",
            name="source",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.DO_NOTHING, to="Jobs.jobsources"
            ),
        ),
        migrations.AddField(
            model_name="jobcollectionlogs",
            name="source",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.DO_NOTHING, to="Jobs.jobsources"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="jobmatchscores",
            unique_together={("user", "job")},
        ),
        migrations.AlterUniqueTogether(
            name="jobinterests",
            unique_together={("user", "job", "interest_type")},
        ),
        migrations.AlterUniqueTogether(
            name="jobs",
            unique_together={("external_id", "source")},
        ),
    ]
