# Generated by Django 5.1.3 on 2026-07-09 01:14

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Jobs", "0004_alter_jobinterests_user"),
    ]

    operations = [
        migrations.CreateModel(
            name="JobProviders",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", models.CharField(max_length=100, unique=True)),
                (
                    "authentication_method",
                    models.CharField(blank=True, max_length=50, null=True),
                ),
                (
                    "pagination_strategy",
                    models.CharField(blank=True, max_length=50, null=True),
                ),
                (
                    "incremental_sync_strategy",
                    models.CharField(blank=True, max_length=50, null=True),
                ),
                ("supports_etag", models.BooleanField(default=False)),
                ("supports_last_modified", models.BooleanField(default=False)),
                ("supports_webhooks", models.BooleanField(default=False)),
                ("supports_cursor_pagination", models.BooleanField(default=False)),
                ("max_page_size", models.IntegerField(default=100)),
                ("request_timeout", models.IntegerField(default=30)),
                ("retry_policy", models.JSONField(blank=True, null=True)),
                ("rate_limit_rpm", models.IntegerField(default=60)),
                ("max_concurrent_workers", models.IntegerField(default=5)),
                ("cooldown_seconds", models.IntegerField(default=0)),
                (
                    "status_429_history",
                    models.JSONField(blank=True, default=list, null=True),
                ),
            ],
            options={
                "db_table": "job_providers",
                "managed": True,
            },
        ),
        migrations.CreateModel(
            name="SystemConfig",
            fields=[
                (
                    "key",
                    models.CharField(max_length=255, primary_key=True, serialize=False),
                ),
                ("value", models.JSONField()),
                ("description", models.TextField(blank=True, null=True)),
            ],
            options={
                "db_table": "system_config",
                "managed": True,
            },
        ),
        migrations.RemoveField(
            model_name="jobsources",
            name="rate_limit_per_minute",
        ),
        migrations.AddField(
            model_name="jobs",
            name="job_hash",
            field=models.CharField(blank=True, max_length=64, null=True, unique=True),
        ),
        migrations.AddField(
            model_name="jobsources",
            name="expiration_interval",
            field=models.DurationField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="jobsources",
            name="verification_interval",
            field=models.DurationField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name="JobProcessingState",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("capability_statuses", models.JSONField(default=dict)),
                ("overall_status", models.CharField(default="PENDING", max_length=20)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "job",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="processing_state",
                        to="Jobs.jobs",
                    ),
                ),
            ],
            options={
                "db_table": "job_processing_state",
                "managed": True,
            },
        ),
        migrations.AddField(
            model_name="jobsources",
            name="provider",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="sources",
                to="Jobs.jobproviders",
            ),
        ),
        migrations.CreateModel(
            name="ScrapeMetadata",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("tier", models.CharField(default="warm", max_length=20)),
                ("priority", models.IntegerField(default=50)),
                ("health_score", models.IntegerField(default=100)),
                (
                    "failure_rate",
                    models.DecimalField(decimal_places=2, default=0.0, max_digits=5),
                ),
                ("average_latency", models.DurationField(blank=True, null=True)),
                ("last_successful_scrape", models.DateTimeField(blank=True, null=True)),
                (
                    "last_job_id_seen",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                ("etag", models.CharField(blank=True, max_length=255, null=True)),
                ("jobs_found_last_run", models.IntegerField(default=0)),
                (
                    "average_update_frequency",
                    models.DurationField(blank=True, null=True),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "source",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="scrape_metadata",
                        to="Jobs.jobsources",
                    ),
                ),
            ],
            options={
                "db_table": "scrape_metadata",
                "managed": True,
            },
        ),
        migrations.CreateModel(
            name="JobEnrichments",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("capability_name", models.CharField(max_length=100)),
                ("result", models.JSONField()),
                ("model_name", models.CharField(blank=True, max_length=100, null=True)),
                (
                    "model_version",
                    models.CharField(blank=True, max_length=50, null=True),
                ),
                (
                    "prompt_version",
                    models.CharField(blank=True, max_length=50, null=True),
                ),
                (
                    "confidence_score",
                    models.DecimalField(
                        blank=True, decimal_places=4, max_digits=5, null=True
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "job",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="enrichments",
                        to="Jobs.jobs",
                    ),
                ),
            ],
            options={
                "db_table": "job_enrichments",
                "managed": True,
                "indexes": [
                    models.Index(
                        fields=["job", "capability_name", "-created_at"],
                        name="job_enrichm_job_id_312b60_idx",
                    )
                ],
            },
        ),
    ]
