# Generated by Django 5.2.8 on 2025-11-19 12:10

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="NewsArticle",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("title", models.CharField(max_length=500)),
                ("description", models.TextField(blank=True, null=True)),
                ("url", models.TextField(unique=True)),
                ("published_at", models.DateTimeField()),
                ("source", models.CharField(blank=True, max_length=200, null=True)),
                ("category", models.CharField(blank=True, max_length=50, null=True)),
                (
                    "relevance_score",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=4, null=True
                    ),
                ),
                ("keywords", models.JSONField(blank=True, null=True)),
                ("topics", models.JSONField(blank=True, null=True)),
                ("scraped_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(blank=True, null=True)),
                ("updated_at", models.DateTimeField(blank=True, null=True)),
            ],
            options={
                "db_table": "news_articles",
                "managed": True,
            },
        ),
    ]
