# Generated by Django 5.2.8 on 2025-11-22 09:18

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("News", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="NewsArticles",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("title", models.CharField(max_length=500)),
                ("url", models.TextField(unique=True)),
                ("source", models.CharField(blank=True, max_length=200, null=True)),
                ("published_at", models.DateTimeField()),
                ("summary", models.TextField(blank=True, null=True)),
                ("content", models.TextField(blank=True, null=True)),
                ("tags", models.JSONField(blank=True, null=True)),
                ("topics", models.JSONField(blank=True, null=True)),
                (
                    "sentiment_score",
                    models.DecimalField(
                        blank=True, decimal_places=3, max_digits=4, null=True
                    ),
                ),
                ("fetched_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(blank=True, null=True)),
                ("updated_at", models.DateTimeField(blank=True, null=True)),
            ],
            options={
                "db_table": "news_articles",
                "managed": True,
            },
        ),
        migrations.DeleteModel(
            name="NewsArticle",
        ),
    ]
