# Generated by Django 5.2.8 on 2025-11-08 00:23

import django.contrib.postgres.fields
import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Companies",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("slug", models.CharField(max_length=255, unique=True)),
                ("description", models.TextField(blank=True, null=True)),
                ("website", models.TextField(blank=True, null=True)),
                ("logo_url", models.TextField(blank=True, null=True)),
                ("industry", models.CharField(blank=True, max_length=100, null=True)),
                (
                    "company_size",
                    models.CharField(blank=True, max_length=50, null=True),
                ),
                ("tier", models.CharField(blank=True, max_length=50, null=True)),
                ("location", models.CharField(blank=True, max_length=255, null=True)),
                ("founded_year", models.IntegerField(blank=True, null=True)),
                ("careers_page_url", models.TextField(blank=True, null=True)),
                (
                    "tech_stack",
                    django.contrib.postgres.fields.ArrayField(
                        base_field=models.CharField(max_length=100),
                        blank=True,
                        default=list,
                        null=True,
                        size=None,
                    ),
                ),
                (
                    "benefits",
                    django.contrib.postgres.fields.ArrayField(
                        base_field=models.CharField(max_length=200),
                        blank=True,
                        default=list,
                        null=True,
                        size=None,
                    ),
                ),
                (
                    "valuation",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=15, null=True
                    ),
                ),
                ("employee_count", models.IntegerField(blank=True, null=True)),
                (
                    "rating",
                    models.DecimalField(
                        blank=True, decimal_places=1, max_digits=2, null=True
                    ),
                ),
                ("review_count", models.IntegerField(blank=True, null=True)),
                ("is_actively_hiring", models.BooleanField(blank=True, null=True)),
                (
                    "avg_salary_min",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=10, null=True
                    ),
                ),
                (
                    "avg_salary_max",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=10, null=True
                    ),
                ),
                ("is_monitored", models.BooleanField(blank=True, null=True)),
                ("last_job_scrape", models.DateTimeField(blank=True, null=True)),
                ("last_news_check", models.DateTimeField(blank=True, null=True)),
                ("total_jobs_posted", models.IntegerField(blank=True, null=True)),
                ("active_jobs_count", models.IntegerField(blank=True, null=True)),
                ("jobs_last_30_days", models.IntegerField(blank=True, null=True)),
                ("created_at", models.DateTimeField(blank=True, null=True)),
                ("updated_at", models.DateTimeField(blank=True, null=True)),
                ("data_freshness_score", models.IntegerField(blank=True, null=True)),
            ],
            options={
                "db_table": "companies",
                "managed": True,
            },
        ),
        migrations.CreateModel(
            name="MarketInsights",
            fields=[
                ("id", models.UUIDField(primary_key=True, serialize=False)),
                (
                    "insight_type",
                    models.CharField(blank=True, max_length=30, null=True),
                ),
                ("title", models.CharField(max_length=200)),
                ("description", models.TextField()),
                (
                    "metric_value",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=15, null=True
                    ),
                ),
                ("metric_unit", models.CharField(blank=True, max_length=50, null=True)),
                ("trend_data", models.JSONField(blank=True, null=True)),
                ("industry", models.CharField(blank=True, max_length=100, null=True)),
                ("region", models.CharField(blank=True, max_length=100, null=True)),
                (
                    "time_period",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                (
                    "confidence_score",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=3, null=True
                    ),
                ),
                ("data_sources", models.TextField(blank=True, null=True)),
                ("calculation_date", models.DateTimeField(blank=True, null=True)),
                ("expires_at", models.DateTimeField(blank=True, null=True)),
            ],
            options={
                "db_table": "market_insights",
                "managed": True,
            },
        ),
        migrations.CreateModel(
            name="CompanyMonitoringJobs",
            fields=[
                ("id", models.UUIDField(primary_key=True, serialize=False)),
                ("job_type", models.CharField(blank=True, max_length=30, null=True)),
                ("status", models.CharField(blank=True, max_length=20, null=True)),
                ("started_at", models.DateTimeField(blank=True, null=True)),
                ("completed_at", models.DateTimeField(blank=True, null=True)),
                ("duration_seconds", models.IntegerField(blank=True, null=True)),
                ("items_processed", models.IntegerField(blank=True, null=True)),
                ("items_created", models.IntegerField(blank=True, null=True)),
                ("items_updated", models.IntegerField(blank=True, null=True)),
                ("errors_count", models.IntegerField(blank=True, null=True)),
                ("parameters", models.JSONField(blank=True, null=True)),
                ("results", models.JSONField(blank=True, null=True)),
                ("error_details", models.TextField(blank=True, null=True)),
                ("created_at", models.DateTimeField(blank=True, null=True)),
                (
                    "company",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        to="Companies.companies",
                    ),
                ),
            ],
            options={
                "db_table": "company_monitoring_jobs",
                "managed": True,
            },
        ),
        migrations.CreateModel(
            name="CompanyNews",
            fields=[
                ("id", models.UUIDField(primary_key=True, serialize=False)),
                ("title", models.CharField(max_length=500)),
                ("url", models.TextField()),
                ("source", models.CharField(blank=True, max_length=100, null=True)),
                ("published_date", models.DateTimeField()),
                ("news_type", models.CharField(blank=True, max_length=20, null=True)),
                ("relevance", models.CharField(blank=True, max_length=20, null=True)),
                ("summary", models.TextField(blank=True, null=True)),
                (
                    "sentiment_score",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=3, null=True
                    ),
                ),
                ("keywords", models.TextField(blank=True, null=True)),
                ("scraped_at", models.DateTimeField(blank=True, null=True)),
                ("is_featured", models.BooleanField(blank=True, null=True)),
                ("view_count", models.IntegerField(blank=True, null=True)),
                (
                    "company",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        to="Companies.companies",
                    ),
                ),
            ],
            options={
                "db_table": "company_news",
                "managed": True,
            },
        ),
        migrations.CreateModel(
            name="IndustryTrends",
            fields=[
                ("id", models.UUIDField(primary_key=True, serialize=False)),
                ("industry", models.CharField(max_length=100)),
                ("trend_type", models.CharField(blank=True, max_length=20, null=True)),
                ("metric_name", models.CharField(max_length=200)),
                ("current_value", models.DecimalField(decimal_places=2, max_digits=15)),
                (
                    "previous_value",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=15, null=True
                    ),
                ),
                (
                    "change_percentage",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=5, null=True
                    ),
                ),
                ("period_start", models.DateField()),
                ("period_end", models.DateField()),
                ("calculation_date", models.DateTimeField(blank=True, null=True)),
                (
                    "data_source",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                (
                    "confidence_score",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=3, null=True
                    ),
                ),
            ],
            options={
                "db_table": "industry_trends",
                "managed": True,
                "unique_together": {
                    ("industry", "trend_type", "metric_name", "period_end")
                },
            },
        ),
    ]
