# Generated by Django 5.2.8 on 2025-12-21 18:46

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Companies", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="TechTrend",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", models.CharField(max_length=100, unique=True)),
                ("category", models.CharField(max_length=50)),
                ("popularity_score", models.FloatField(default=0)),
                ("growth_percentage", models.FloatField(default=0)),
                ("demand_rank", models.IntegerField(default=0)),
                ("social_volume", models.IntegerField(default=0)),
                ("sentiment_score", models.FloatField(default=0.5)),
                ("last_updated", models.DateTimeField(auto_now=True)),
                ("description", models.TextField(blank=True, null=True)),
                ("is_active", models.BooleanField(default=True)),
            ],
            options={
                "db_table": "tech_trends",
                "managed": True,
            },
        ),
        migrations.CreateModel(
            name="TechTrendNews",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("title", models.CharField(max_length=500)),
                ("url", models.TextField()),
                ("source", models.CharField(max_length=100)),
                ("published_at", models.DateTimeField()),
                ("snippet", models.TextField(blank=True, null=True)),
                ("sentiment", models.FloatField(default=0.5)),
                (
                    "tech",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="news",
                        to="Companies.techtrend",
                    ),
                ),
            ],
            options={
                "db_table": "tech_trend_news",
                "managed": True,
            },
        ),
    ]
