# Generated by Django 5.1.3 on 2026-07-09 01:14

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Companies", "0002_techtrend_techtrendnews"),
    ]

    operations = [
        migrations.CreateModel(
            name="CompanyDocument",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("source_url", models.TextField()),
                ("content_raw", models.TextField()),
                ("content_markdown", models.TextField(blank=True, null=True)),
                ("crawl_timestamp", models.DateTimeField(auto_now_add=True)),
                (
                    "company",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="documents",
                        to="Companies.companies",
                    ),
                ),
            ],
            options={
                "db_table": "company_documents",
                "managed": True,
            },
        ),
        migrations.CreateModel(
            name="CompanyKnowledge",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("fact_type", models.CharField(max_length=100)),
                ("content", models.TextField()),
                (
                    "confidence_score",
                    models.DecimalField(decimal_places=2, max_digits=3),
                ),
                ("model_version", models.CharField(max_length=100)),
                ("evidence_reference", models.TextField(blank=True, null=True)),
                ("extracted_at", models.DateTimeField(auto_now_add=True)),
                (
                    "company",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="knowledge",
                        to="Companies.companies",
                    ),
                ),
                (
                    "document",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="Companies.companydocument",
                    ),
                ),
            ],
            options={
                "db_table": "company_knowledge",
                "managed": True,
            },
        ),
        migrations.CreateModel(
            name="CompanyObservation",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("observation_type", models.CharField(max_length=100)),
                ("value", models.JSONField()),
                ("observed_at", models.DateTimeField(auto_now_add=True)),
                (
                    "company",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="observations",
                        to="Companies.companies",
                    ),
                ),
            ],
            options={
                "db_table": "company_observations",
                "managed": True,
            },
        ),
        migrations.CreateModel(
            name="CompanySource",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("url", models.TextField(unique=True)),
                ("source_type", models.CharField(max_length=50)),
                ("is_active", models.BooleanField(default=True)),
                ("last_crawled_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "company",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="sources",
                        to="Companies.companies",
                    ),
                ),
            ],
            options={
                "db_table": "company_sources",
                "managed": True,
            },
        ),
        migrations.AddField(
            model_name="companydocument",
            name="source",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="Companies.companysource",
            ),
        ),
    ]
