# Generated by Django 5.2.8 on 2025-11-06 03:47

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Users",
            fields=[
                ("id", models.UUIDField(primary_key=True, serialize=False)),
                ("email", models.CharField(max_length=255, unique=True)),
                ("name", models.CharField(max_length=255)),
                ("password_hash", models.TextField(blank=True, null=True)),
                ("google_id", models.CharField(blank=True, max_length=255, null=True)),
                ("github_id", models.CharField(blank=True, max_length=255, null=True)),
                ("email_verified", models.BooleanField(blank=True, null=True)),
                ("email_verification_token", models.TextField(blank=True, null=True)),
                ("last_login_at", models.DateTimeField(blank=True, null=True)),
                (
                    "subscription_tier",
                    models.CharField(
                        blank=True, default="free", max_length=50, null=True
                    ),
                ),
                (
                    "subscription_status",
                    models.CharField(
                        blank=True, default="active", max_length=50, null=True
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("gmail_sync_enabled", models.BooleanField(blank=True, null=True)),
                ("gmail_credentials", models.TextField(blank=True, null=True)),
                ("gmail_last_sync", models.DateTimeField(blank=True, null=True)),
                ("avatar_url", models.TextField(blank=True, null=True)),
                ("bio", models.TextField(blank=True, null=True)),
                ("location", models.CharField(blank=True, max_length=255, null=True)),
                ("resume_url", models.TextField(blank=True, null=True)),
                ("preferred_work_type", models.TextField(blank=True, null=True)),
                ("preferred_locations", models.TextField(blank=True, null=True)),
                (
                    "target_salary_min",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=10, null=True
                    ),
                ),
                (
                    "target_salary_max",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=10, null=True
                    ),
                ),
                ("created_at", models.DateTimeField(blank=True, null=True)),
                ("updated_at", models.DateTimeField(blank=True, null=True)),
            ],
            options={
                "db_table": "users",
                "managed": True,
            },
        ),
        migrations.CreateModel(
            name="UserSkills",
            fields=[
                ("id", models.UUIDField(primary_key=True, serialize=False)),
                ("skill_name", models.CharField(max_length=100)),
                (
                    "skill_category",
                    models.CharField(blank=True, max_length=50, null=True),
                ),
                (
                    "proficiency_level",
                    models.CharField(blank=True, max_length=20, null=True),
                ),
                (
                    "years_of_experience",
                    models.DecimalField(
                        blank=True, decimal_places=1, max_digits=3, null=True
                    ),
                ),
                ("is_verified", models.BooleanField(blank=True, null=True)),
                (
                    "verified_by",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                ("added_date", models.DateField(blank=True, null=True)),
                ("last_used_date", models.DateField(blank=True, null=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "user_skills",
                "managed": True,
                "unique_together": {("user", "skill_name")},
            },
        ),
    ]
