# Generated by Django 5.2.8 on 2025-11-08 00:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Oauth", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="UserProfiles",
            fields=[
                ("id", models.UUIDField(primary_key=True, serialize=False)),
                (
                    "current_title",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "years_of_experience",
                    models.DecimalField(
                        blank=True, decimal_places=1, max_digits=3, null=True
                    ),
                ),
                (
                    "education_level",
                    models.CharField(blank=True, max_length=50, null=True),
                ),
                ("preferred_industries", models.TextField(blank=True, null=True)),
                (
                    "target_role",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "target_salary_min",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=10, null=True
                    ),
                ),
                (
                    "target_salary_max",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=10, null=True
                    ),
                ),
                ("target_locations", models.TextField(blank=True, null=True)),
                ("willing_to_relocate", models.BooleanField(blank=True, null=True)),
                ("open_to_remote", models.BooleanField(blank=True, null=True)),
                ("profile_completeness", models.IntegerField(blank=True, null=True)),
                ("last_updated", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(blank=True, null=True)),
                ("updated_at", models.DateTimeField(blank=True, null=True)),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.DO_NOTHING, to="Oauth.users"
                    ),
                ),
            ],
            options={
                "db_table": "user_profiles",
                "managed": True,
            },
        ),
    ]
