# Generated by Django 5.2.8 on 2025-11-10 07:12

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Oauth", "0002_userprofiles"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name="userskills",
            name="id",
            field=models.UUIDField(
                default=uuid.uuid4, primary_key=True, serialize=False
            ),
        ),
        migrations.CreateModel(
            name="Profile",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, primary_key=True, serialize=False
                    ),
                ),
                ("full_name", models.CharField(blank=True, max_length=100, null=True)),
                ("portfolio", models.URLField(blank=True, null=True)),
                (
                    "phone_number",
                    models.CharField(blank=True, max_length=20, null=True),
                ),
                ("country", models.CharField(blank=True, max_length=20, null=True)),
                ("linkedin_url", models.URLField(blank=True, null=True)),
                ("avatar_id", models.CharField(blank=True, max_length=100, null=True)),
                ("resume_url", models.CharField(blank=True, max_length=255, null=True)),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="EducationBackground",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, primary_key=True, serialize=False
                    ),
                ),
                ("institution", models.CharField(max_length=100)),
                ("joined", models.DateField(blank=True, null=True)),
                ("done", models.BooleanField(default=True)),
                ("completed", models.DateField(blank=True, null=True)),
                (
                    "certification",
                    models.CharField(blank=True, max_length=50, null=True),
                ),
                (
                    "field_of_learning",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                (
                    "profile",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="education",
                        to="Oauth.profile",
                    ),
                ),
            ],
        ),
        migrations.AlterUniqueTogether(
            name="userskills",
            unique_together=set(),
        ),
        migrations.AddField(
            model_name="userskills",
            name="profile",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="Oauth.profile",
            ),
        ),
        migrations.AlterUniqueTogether(
            name="userskills",
            unique_together={("profile", "skill_name")},
        ),
        migrations.CreateModel(
            name="Project",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, primary_key=True, serialize=False
                    ),
                ),
                ("name", models.CharField(max_length=150)),
                ("description", models.TextField(blank=True, null=True)),
                ("tools", models.CharField(blank=True, max_length=255, null=True)),
                ("link", models.URLField(blank=True, null=True)),
                (
                    "profile",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="projects",
                        to="Oauth.profile",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="WorkExperience",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, primary_key=True, serialize=False
                    ),
                ),
                ("title", models.CharField(max_length=100)),
                ("company", models.CharField(max_length=100)),
                ("start_date", models.DateField(blank=True, null=True)),
                ("end_date", models.DateField(blank=True, null=True)),
                ("location", models.CharField(blank=True, max_length=100, null=True)),
                ("description", models.TextField(blank=True, null=True)),
                (
                    "profile",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="experiences",
                        to="Oauth.profile",
                    ),
                ),
            ],
        ),
        migrations.RemoveField(
            model_name="userskills",
            name="user",
        ),
    ]
