# Generated by Django 5.2.8 on 2025-11-13 18:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Oauth", "0006_add_profile_fields"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="users",
            name="preferred_locations",
        ),
        migrations.RemoveField(
            model_name="users",
            name="preferred_work_type",
        ),
        migrations.RemoveField(
            model_name="users",
            name="target_salary_max",
        ),
        migrations.RemoveField(
            model_name="users",
            name="target_salary_min",
        ),
        migrations.AlterField(
            model_name="educationbackground",
            name="profile",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="education_background",
                to="Oauth.profile",
            ),
        ),
        migrations.AlterField(
            model_name="userskills",
            name="profile",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="skills",
                to="Oauth.profile",
            ),
        ),
    ]
