# Generated by Django 5.2.8 on 2025-12-02 00:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Oauth", "0007_remove_users_preferred_locations_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="profile",
            name="gmail_credentials",
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="profile",
            name="gmail_sync_enabled",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="profile",
            name="gmail_last_sync",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="profile",
            name="calendar_credentials",
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="profile",
            name="calendar_sync_enabled",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="profile",
            name="calendar_last_sync",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]