# Generated by Django 5.2.8 on 2025-12-21 13:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Oauth", "0008_add_gmail_calendar_fields_to_profile"),
    ]

    operations = [
        migrations.AddField(
            model_name="profile",
            name="resume_data",
            field=models.JSONField(blank=True, null=True),
        ),
    ]
