# Generated by Django 5.2.8 on 2025-12-21 14:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Oauth", "0009_profile_resume_data"),
    ]

    operations = [
        migrations.AddField(
            model_name="jobpreferences",
            name="company_types",
            field=models.TextField(blank=True, null=True),
        ),
    ]
