# Generated by Django 5.2.8 on 2025-12-21 14:46

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Oauth", "0010_jobpreferences_company_types"),
    ]

    operations = [
        migrations.CreateModel(
            name="CareerGoals",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, primary_key=True, serialize=False
                    ),
                ),
                ("looking_for", models.TextField(blank=True, null=True)),
                ("deal_breakers", models.TextField(blank=True, null=True)),
                ("nice_to_haves", models.TextField(blank=True, null=True)),
                (
                    "profile",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="career_goals",
                        to="Oauth.profile",
                    ),
                ),
            ],
        ),
    ]
