# Generated by Django 5.2.8 on 2026-06-22 04:01

from django.conf import settings
from django.db import migrations, models


def migrate_legacy_users_to_profiles(apps, schema_editor):
    Users = apps.get_model('Oauth', 'Users')
    Profile = apps.get_model('Oauth', 'Profile')
    auth_app_label, auth_model_name = settings.AUTH_USER_MODEL.split('.')
    AuthUser = apps.get_model(auth_app_label, auth_model_name)

    for legacy_user in Users.objects.all().iterator():
        auth_user = AuthUser.objects.filter(email__iexact=legacy_user.email).first()
        if not auth_user:
            continue

        profile, _ = Profile.objects.get_or_create(user=auth_user)
        update_fields = []

        mappings = {
            'google_id': legacy_user.google_id,
            'github_id': legacy_user.github_id,
            'email_verified': legacy_user.email_verified,
            'email_verification_token': legacy_user.email_verification_token,
            'last_login_at': legacy_user.last_login_at,
            'subscription_tier': legacy_user.subscription_tier,
            'subscription_status': legacy_user.subscription_status,
            'bio': legacy_user.bio,
            'location': legacy_user.location,
            'resume_url': legacy_user.resume_url,
            'gmail_sync_enabled': legacy_user.gmail_sync_enabled,
            'gmail_credentials': legacy_user.gmail_credentials,
            'gmail_last_sync': legacy_user.gmail_last_sync,
        }
        for field_name, value in mappings.items():
            if value in (None, ''):
                continue
            setattr(profile, field_name, value)
            update_fields.append(field_name)

        if legacy_user.name and not profile.full_name:
            profile.full_name = legacy_user.name
            update_fields.append('full_name')

        if update_fields:
            profile.save(update_fields=sorted(set(update_fields)))

        if legacy_user.is_active != auth_user.is_active:
            auth_user.is_active = legacy_user.is_active
            auth_user.save(update_fields=['is_active'])


class Migration(migrations.Migration):

    dependencies = [
        ('Applications', '0004_alter_applications_user_alter_emailtracking_user'),
        ('Jobs', '0004_alter_jobinterests_user'),
        ('Oauth', '0011_careergoals'),
        ('Personalization', '0002_alter_learningpaths_user_alter_skillgapanalyses_user_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='bio',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='email_verification_token',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='email_verified',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='github_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='google_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='last_login_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='subscription_status',
            field=models.CharField(blank=True, default='active', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='subscription_tier',
            field=models.CharField(blank=True, default='free', max_length=50, null=True),
        ),
        migrations.RunPython(migrate_legacy_users_to_profiles, migrations.RunPython.noop),
        migrations.DeleteModel(
            name='UserProfiles',
        ),
        migrations.DeleteModel(
            name='Users',
        ),
    ]
