# Generated by Django 6.0.5 on 2026-06-29 05:34

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Oauth", "0012_profile_bio_profile_email_verification_token_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="project",
            name="measurable_impact",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="project",
            name="metadata",
            field=models.JSONField(blank=True, default=dict, null=True),
        ),
        migrations.AddField(
            model_name="project",
            name="outcomes",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="project",
            name="skills_demonstrated",
            field=models.ManyToManyField(
                blank=True, related_name="projects_demonstrated", to="Oauth.userskills"
            ),
        ),
        migrations.AddField(
            model_name="userskills",
            name="confidence_score",
            field=models.DecimalField(
                blank=True, decimal_places=3, max_digits=4, null=True
            ),
        ),
        migrations.AddField(
            model_name="userskills",
            name="last_verified_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="userskills",
            name="metadata",
            field=models.JSONField(blank=True, default=dict, null=True),
        ),
        migrations.AddField(
            model_name="userskills",
            name="proficiency_score",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="userskills",
            name="verification_source",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="workexperience",
            name="achievements",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="workexperience",
            name="business_impact",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="workexperience",
            name="metadata",
            field=models.JSONField(blank=True, default=dict, null=True),
        ),
        migrations.AddField(
            model_name="workexperience",
            name="skills_demonstrated",
            field=models.ManyToManyField(
                blank=True, related_name="work_experiences", to="Oauth.userskills"
            ),
        ),
        migrations.AddField(
            model_name="workexperience",
            name="technologies_used",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name="Evidence",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, primary_key=True, serialize=False
                    ),
                ),
                (
                    "evidence_type",
                    models.CharField(
                        choices=[
                            ("resume_bullet", "Resume Bullet"),
                            ("github_repo", "GitHub Repository"),
                            ("portfolio_project", "Portfolio Project"),
                            ("work_experience", "Work Experience"),
                            ("certification", "Certification"),
                            ("assessment", "Assessment"),
                            ("recommendation", "Recommendation"),
                            ("interview_feedback", "Interview Feedback"),
                            ("application_outcome", "Application Outcome"),
                            ("other", "Other"),
                        ],
                        max_length=50,
                    ),
                ),
                ("title", models.CharField(blank=True, max_length=255, null=True)),
                ("description", models.TextField(blank=True, null=True)),
                ("url", models.URLField(blank=True, null=True)),
                ("metadata", models.JSONField(blank=True, default=dict, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "profile",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="evidence",
                        to="Oauth.profile",
                    ),
                ),
            ],
            options={
                "db_table": "evidence",
                "managed": True,
            },
        ),
        migrations.CreateModel(
            name="DecisionLog",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, primary_key=True, serialize=False
                    ),
                ),
                ("decision_type", models.CharField(max_length=150)),
                ("inputs", models.JSONField(default=dict)),
                ("conclusion", models.JSONField(default=dict)),
                ("reasoning_process", models.TextField(blank=True, null=True)),
                (
                    "confidence",
                    models.DecimalField(decimal_places=3, default=0.0, max_digits=4),
                ),
                (
                    "strategy_used",
                    models.CharField(blank=True, max_length=50, null=True),
                ),
                (
                    "model_version",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                (
                    "twin_version_id",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "profile",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="decision_history",
                        to="Oauth.profile",
                    ),
                ),
                (
                    "evidence_referenced",
                    models.ManyToManyField(
                        blank=True,
                        related_name="decisions_supported",
                        to="Oauth.evidence",
                    ),
                ),
            ],
            options={
                "db_table": "decision_logs",
                "managed": True,
            },
        ),
        migrations.AddField(
            model_name="project",
            name="evidence",
            field=models.ManyToManyField(
                blank=True, related_name="projects_supported", to="Oauth.evidence"
            ),
        ),
        migrations.AddField(
            model_name="userskills",
            name="evidence",
            field=models.ManyToManyField(
                blank=True, related_name="skills_supported", to="Oauth.evidence"
            ),
        ),
        migrations.AddField(
            model_name="workexperience",
            name="evidence",
            field=models.ManyToManyField(
                blank=True,
                related_name="work_experiences_supported",
                to="Oauth.evidence",
            ),
        ),
        migrations.CreateModel(
            name="EvidenceNode",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, primary_key=True, serialize=False
                    ),
                ),
                ("node_type", models.CharField(max_length=50)),
                ("source", models.CharField(max_length=100)),
                ("url", models.URLField(blank=True, null=True)),
                ("title", models.CharField(blank=True, max_length=255, null=True)),
                ("description", models.TextField(blank=True, null=True)),
                ("metadata", models.JSONField(blank=True, default=dict, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "profile",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="evidence_nodes",
                        to="Oauth.profile",
                    ),
                ),
                (
                    "related_nodes",
                    models.ManyToManyField(
                        blank=True, related_name="supported_by", to="Oauth.evidencenode"
                    ),
                ),
            ],
            options={
                "db_table": "evidence_nodes",
            },
        ),
        migrations.CreateModel(
            name="CapabilityNode",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, primary_key=True, serialize=False
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("category", models.CharField(blank=True, max_length=50, null=True)),
                (
                    "verification_score",
                    models.DecimalField(decimal_places=2, default=0.0, max_digits=5),
                ),
                (
                    "depth_score",
                    models.DecimalField(decimal_places=2, default=0.0, max_digits=5),
                ),
                (
                    "freshness_score",
                    models.DecimalField(decimal_places=2, default=0.0, max_digits=5),
                ),
                (
                    "market_relevance",
                    models.DecimalField(decimal_places=2, default=0.0, max_digits=5),
                ),
                (
                    "capability_score",
                    models.DecimalField(decimal_places=2, default=0.0, max_digits=5),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "parent_capabilities",
                    models.ManyToManyField(
                        blank=True,
                        related_name="sub_capabilities",
                        to="Oauth.capabilitynode",
                    ),
                ),
                (
                    "profile",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="capability_nodes",
                        to="Oauth.profile",
                    ),
                ),
                (
                    "supported_by_evidence",
                    models.ManyToManyField(
                        blank=True,
                        related_name="supports_capabilities",
                        to="Oauth.evidencenode",
                    ),
                ),
            ],
            options={
                "db_table": "capability_nodes",
            },
        ),
        migrations.CreateModel(
            name="Insight",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, primary_key=True, serialize=False
                    ),
                ),
                (
                    "insight_type",
                    models.CharField(
                        choices=[
                            ("strength", "Strength"),
                            ("weakness", "Weakness"),
                            ("opportunity", "Opportunity"),
                            ("risk", "Risk"),
                            ("recommendation", "Recommendation"),
                            ("obstacle", "Obstacle"),
                        ],
                        max_length=50,
                    ),
                ),
                ("description", models.TextField()),
                ("source", models.CharField(blank=True, max_length=255, null=True)),
                ("severity", models.CharField(blank=True, max_length=50, null=True)),
                (
                    "confidence",
                    models.DecimalField(decimal_places=3, default=0.5, max_digits=4),
                ),
                (
                    "affected_companies",
                    models.JSONField(blank=True, default=list, null=True),
                ),
                (
                    "affected_roles",
                    models.JSONField(blank=True, default=list, null=True),
                ),
                (
                    "recommended_actions",
                    models.JSONField(blank=True, default=list, null=True),
                ),
                ("is_resolved", models.BooleanField(default=False)),
                ("resolved_at", models.DateTimeField(blank=True, null=True)),
                ("metadata", models.JSONField(blank=True, default=dict, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "profile",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="insights",
                        to="Oauth.profile",
                    ),
                ),
            ],
            options={
                "db_table": "insights",
                "managed": True,
            },
        ),
        migrations.CreateModel(
            name="IntelligenceSnapshot",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, primary_key=True, serialize=False
                    ),
                ),
                ("version", models.IntegerField()),
                ("target_role", models.CharField(max_length=255)),
                (
                    "career_readiness",
                    models.DecimalField(decimal_places=2, default=0.0, max_digits=5),
                ),
                ("estimated_time_months", models.IntegerField(blank=True, null=True)),
                ("capability_state", models.JSONField(default=dict)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "previous_snapshot",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="Oauth.intelligencesnapshot",
                    ),
                ),
                (
                    "profile",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="intelligence_snapshots",
                        to="Oauth.profile",
                    ),
                ),
            ],
            options={
                "db_table": "intelligence_snapshots",
                "unique_together": {("profile", "version")},
            },
        ),
        migrations.CreateModel(
            name="NavigatorAction",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, primary_key=True, serialize=False
                    ),
                ),
                ("sequence_order", models.IntegerField()),
                ("action_type", models.CharField(max_length=50)),
                ("title", models.CharField(max_length=255)),
                ("description", models.TextField(blank=True, null=True)),
                (
                    "roi_impact_percentage",
                    models.DecimalField(decimal_places=2, default=0.0, max_digits=5),
                ),
                ("is_completed", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "snapshot",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="navigator_actions",
                        to="Oauth.intelligencesnapshot",
                    ),
                ),
            ],
            options={
                "db_table": "navigator_actions",
                "ordering": ["sequence_order"],
            },
        ),
        migrations.CreateModel(
            name="SkillProgress",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, primary_key=True, serialize=False
                    ),
                ),
                ("previous_proficiency", models.IntegerField(blank=True, null=True)),
                ("new_proficiency", models.IntegerField()),
                ("reason", models.TextField(blank=True, null=True)),
                ("metadata", models.JSONField(blank=True, default=dict, null=True)),
                ("timestamp", models.DateTimeField(auto_now_add=True)),
                (
                    "evidence",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="skill_progress_events",
                        to="Oauth.evidence",
                    ),
                ),
                (
                    "user_skill",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="progress_history",
                        to="Oauth.userskills",
                    ),
                ),
            ],
            options={
                "db_table": "skill_progress",
                "managed": True,
            },
        ),
    ]
