# Generated by Django 6.0.5 on 2026-07-05 09:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Oauth", "0013_project_measurable_impact_project_metadata_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="jobpreferences",
            name="auto_apply_enabled",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="jobpreferences",
            name="auto_apply_threshold",
            field=models.IntegerField(default=80),
        ),
    ]
