# Generated by Django 6.0.5 on 2026-07-21 06:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Oauth", "0014_jobpreferences_auto_apply_enabled_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="profile",
            name="github_credentials",
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="profile",
            name="github_last_sync",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="profile",
            name="github_sync_enabled",
            field=models.BooleanField(default=False),
        ),
    ]
